/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ImportRouteImport } from './routes/import'
import { Route as AnalysesIndexRouteImport } from './routes/analyses.index'
import { Route as AnalysesIdRouteImport } from './routes/analyses.$id'
import { Route as CisIndexRouteImport } from './routes/cis.index'
import { Route as CisIdRouteImport } from './routes/cis.$id'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesIndexRoute = AnalysesIndexRouteImport.update({
  id: '/analyses/',
  path: '/analyses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesIdRoute = AnalysesIdRouteImport.update({
  id: '/analyses/$id',
  path: '/analyses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CisIndexRoute = CisIndexRouteImport.update({
  id: '/cis/',
  path: '/cis/',
  getParentRoute: () => rootRouteImport,
} as any)
const CisIdRoute = CisIdRouteImport.update({
  id: '/cis/$id',
  path: '/cis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/import': typeof ImportRoute
  '/analyses/$id': typeof AnalysesIdRoute
  '/cis/$id': typeof CisIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/analyses/': typeof AnalysesIndexRoute
  '/cis/': typeof CisIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/import': typeof ImportRoute
  '/analyses/$id': typeof AnalysesIdRoute
  '/cis/$id': typeof CisIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/analyses': typeof AnalysesIndexRoute
  '/cis': typeof CisIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/import': typeof ImportRoute
  '/analyses/$id': typeof AnalysesIdRoute
  '/cis/$id': typeof CisIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/analyses/': typeof AnalysesIndexRoute
  '/cis/': typeof CisIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/import'
    | '/analyses/$id'
    | '/cis/$id'
    | '/services/$id'
    | '/analyses/'
    | '/cis/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/import'
    | '/analyses/$id'
    | '/cis/$id'
    | '/services/$id'
    | '/analyses'
    | '/cis'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/import'
    | '/analyses/$id'
    | '/cis/$id'
    | '/services/$id'
    | '/analyses/'
    | '/cis/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  ImportRoute: typeof ImportRoute
  AnalysesIdRoute: typeof AnalysesIdRoute
  CisIdRoute: typeof CisIdRoute
  ServicesIdRoute: typeof ServicesIdRoute
  AnalysesIndexRoute: typeof AnalysesIndexRoute
  CisIndexRoute: typeof CisIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses/': {
      id: '/analyses/'
      path: '/analyses'
      fullPath: '/analyses/'
      preLoaderRoute: typeof AnalysesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses/$id': {
      id: '/analyses/$id'
      path: '/analyses/$id'
      fullPath: '/analyses/$id'
      preLoaderRoute: typeof AnalysesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cis/': {
      id: '/cis/'
      path: '/cis'
      fullPath: '/cis/'
      preLoaderRoute: typeof CisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cis/$id': {
      id: '/cis/$id'
      path: '/cis/$id'
      fullPath: '/cis/$id'
      preLoaderRoute: typeof CisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  ImportRoute: ImportRoute,
  AnalysesIdRoute: AnalysesIdRoute,
  CisIdRoute: CisIdRoute,
  ServicesIdRoute: ServicesIdRoute,
  AnalysesIndexRoute: AnalysesIndexRoute,
  CisIndexRoute: CisIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
